# Generated by Django 2.1.2 on 2019-08-17 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rasberrypy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('createTime', models.DateTimeField(auto_now=True)),
                ('productKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rasberrypy.Product')),
            ],
        ),
        migrations.AlterField(
            model_name='babypicture',
            name='isReverse',
            field=models.BooleanField(default=False),
        ),
    ]
