# Generated by Django 2.1.2 on 2019-08-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasberrypy', '0002_auto_20190818_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='babysick',
            name='createTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
